# Generated by Django 4.2.7 on 2024-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_end',
            field=models.DateTimeField(default='2024-11-11 00:00'),
            preserve_default=False,
        ),
    ]
